[workspace]
resolver = "3"
members = [
    "crates/xtools-ui",
    "crates/xtools-host",
    "crates/xtools-time",
    "crates/xtools-json",
    "crates/xtools-trans",
]
default-members = [
    "crates/xtools-host",
    "crates/xtools-time",
    "crates/xtools-json",
    "crates/xtools-trans",
]

[workspace.package]
version = "0.2.2"
edition = "2024"
license = "MIT"
rust-version = "1.85"
[workspace.dependencies]
xtools-ui = { path = "crates/xtools-ui" }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
