[package]
name = "xtools-trans"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
slint = "1.17.1"
thiserror = "2.0.20"
ureq = { version = "3.4.0", features = ["json"] }
xtools-ui = { workspace = true, features = ["slint-chrome", "x11-skip-taskbar"] }

[build-dependencies]
slint-build = "1.17.1"
